### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by Filipposcmd** [sam-astro/PricePredictNeuralNetwork#1]
1) How can i open `weightpersistence.dat`?
2)Why i get this error:
`?? Could not sync with server. Please try again later. ??
Unhandled exception. System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at NetManagerConvo.NeuralManager() in D:\Code\PricePredictNeuralNetwork\NetManagerConvo.cs:line 109
   at NeuralNetConsoleCSCopy.Program.Main(String[] args) in D:\Code\PricePredictNeuralNetwork\Program.cs:line 13`
every time i try running the executable?
### Thanks for your time @sam-astro

**Comment by Filipposcmd** [comment]
3) Is there a way i can view the results in a more organized way?

**Comment by sam-astro** [comment]
- `weightpersistence.dat` Is how the weights are stored, it doesn't contain any useful information.
- I just fixed the 404 error, download the new changes.
- You can maybe edit the program to do that? I'm not sure what results you are looking for though.

**Also, importantly:**
This is an old prototype project, and is pretty bad and buggy and slow, so if you want a better neural network system there is the implementation in Unity here: https://github.com/sam-astro/NN-2 .
I didn't make a price predictor, but it would definitely be a lot easier to implement than the other things I made with it, and run a lot better than this one.

**Comment by Filipposcmd** [comment]
> * `weightpersistence.dat` Is how the weights are stored, it doesn't contain any useful information.
> * I just fixed the 404 error, download the new changes.
> * You can maybe edit the program to do that? I'm not sure what results you are looking for though.
> 
> **Also, importantly:** This is an old prototype project, and is pretty bad and buggy and slow, so if you want a better neural network system there is the implementation in Unity here: https://github.com/sam-astro/NN-2 . I didn't make a price predictor, but it would definitely be a lot easier to implement than the other things I made with it, and run a lot better than this one.

Thanks!

**Comment by Filipposcmd** [comment]
I sometines still get the same error:(`?? Could not sync with server. Please try again later. ?? Unhandled exception. System.Net.WebException: The remote server returned an error: (404) Not Found. at System.Net.HttpWebRequest.GetResponse() at System.Net.WebClient.GetWebResponse(WebRequest request) at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream) at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request) at System.Net.WebClient.DownloadString(Uri address) at System.Net.WebClient.DownloadString(String address) at NetManagerConvo.NeuralManager() in D:\Code\PricePredictNeuralNetwork\NetManagerConvo.cs:line 109 at NeuralNetConsoleCSCopy.Program.Main(String[] args) in D:\Code\PricePredictNeuralNetwork\Program.cs:line 13`)

**Comment by sam-astro** [comment]
That is odd, does the version inside the folder `PricePredictNeuralNetwork\bin\Debug\netcoreapp3.1` work for you?

**Comment by Filipposcmd** [comment]
I checkd and... Yes it works!
Also as a quick patch i used the verizion that is in `PricePredictNeuralNetwork-main\Executable\Beta (Ignore this)`
